libreria/urls.py
from django.urls import path
from .views import LibroListView, AutoreDetailViewCB

app_name="libreria"

urlpatterns=[
    path("lista_libri/",LibroListView.as_view(), name="lista_libri"),
    path("autore/<int:pk>", AutoreDetailViewCB.as_view(), name="autore_detail"),
]

news/urls.py
from django.urls import path
from .views import home, ArticoloDetailViewCB, ArticoloListView, GiornalistaDetailViewCB,GiornalistaListView

app_name="news"

urlpatterns=[  
    path('', home, name ="homeview"),
    #path("articoli/<int:pk>", articoloDetailView, name="articolo_detail")
    path("articoli/<int:pk>", ArticoloDetailViewCB.as_view(), name="articolo_detail"),
    path("lista_articoli/", ArticoloListView.as_view(), name="lista_articoli"),
    path("giornalisti/<int:pk>", GiornalistaDetailViewCB.as_view(), name="giornalista_detail"),
    path("lista_giornalisti/", GiornalistaListView.as_view(), name="lista_giornalisti")
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path, include
from prima_app.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index,name='index'),
    path('prima_app/', include('prima_app.urls')),
    path('seconda_app/', include('seconda_app.urls')),
    path('news/', include('news.urls')),
    path('libreria/', include('libreria.urls')),
    path('forms_app/', include('forms_app.urls')),
]

#aggiungiamo a djbango l'authentication url: 
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

libreria/models.py
from django.db import models

class Genere_ma(models.Model):
    genere= models.CharField(max_length=20)

    def __str__(self):
        return self.genere
    class Meta: 
        verbose_name="Genere"
        verbose_name_plural="Generi"

class Autore_ma (models.Model):
    nome= models.CharField(max_length=20)
    cognome= models.CharField(max_length=20)

    def __str__(self):
        return self.cognome
    class Meta: 
        verbose_name="Autore"
        verbose_name_plural="Autori"

class Libro_ma (models.Model): 
    titolo = models.CharField(max_length=20)
    ISBN = models.CharField(max_length=20)
    autore = models.ForeignKey(Autore_ma, on_delete=models.CASCADE, related_name="libri")
    genere = models.ManyToManyField(Genere_ma)

    def __str__(self):
       return self.titolo

    class Meta: 
        verbose_name="Libro"
        verbose_name_plural="Libri"

libreria/views.py
from django.shortcuts import render, get_object_or_404
from .models import Genere_ma, Autore_ma, Libro_ma
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView 


def autoreDetailView(request, pk): 
    autore=get_object_or_404(Autore_ma, pk=pk)
    context={"autore": autore}
    return render(request, "autore_detail.html", context)

class AutoreDetailViewCB(DetailView): 
    model=Autore_ma
    template_name="autore_detail.html"

class LibroListView(ListView): 
    model=Libro_ma
    template_name="lista_libri.html"
    
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context["libri"]= Libro_ma.objects.all()
        return context
        
def index(request):

    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_visits': num_visits,
    }

    # Render the HTML template index.html with the data in the context variable.
    return render(request, 'lista_libri.html', context=context)

libreria/templates/autore.html
{% extends 'base.html'%}

{% block title %}
    {{ autore.cognome}}
{%endblock title%}

{% block content %}
    <h1>{{ autore.cognome }}</h1>
    <h3>{{ autore.nome }}</h3>
{% endblock content %}

libreria/templates/autore_detail.html
{% extends 'base.html'%}

{% block title %}
    {{ autore_ma.cognome}}
{%endblock title%}

{% block content %}
    <h1>{{ autore_ma.cognome }}</h1>
    <h3>{{ autore_ma.nome }}</h3>
    {% for libro in  autore_ma.libri.all %}
        <h4><strong>Titolo: </strong>{{ libro.titolo }}</h4>
        <h5><strong>Genere: </strong>{% for genere in libro.genere.all %}{{ genere }} {% endfor %}</h5>
        <h5><strong>ISBN: </strong>{{ libro.ISBN }}</h5>
        <hr>
    {% endfor %}
{% endblock content %}

libreria/templates/lista_libri.html
{% extends 'base.html'%}

{ %block title% }
    Lista Libri
{ %endblock title% }

{%block content%}
    <h4>Libro: </h4>
    {% for libro in libri %}
        <p><strong>Titolo:</strong>{{libro.titolo}}</a></p>
        <p><strong>Contenuto: </strong>{{libro.genere.all|join:" "}}</p>
        <p><strong>Autore:</strong><a href="{% url 'libreria:autore_detail' libro.autore.id %}">{{libro.autore.nome}},{{libro.autore.cognome}}</a></p>
        <p><strong>ISBN:</strong>{{libro.ISBN}}</p>
        <hr>
    {% endfor %}



<h2>Dynamic content</h2>

<p>The library has the following record counts:</p>

<p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>
{% endblock content %}