forms_app/urls.py
from django.urls import path
from .views import contatti
app_name="forms_app"

urlpatterns = [
    path('contattaci/', contatti, name= 'contatti')
]

libreria/urls.py
from django.urls import path
from .views import LibroListView, AutoreDetailViewCB

app_name="libreria"

urlpatterns=[
    path("lista_libri/",LibroListView.as_view(), name="lista_libri"),
    path("autore/<int:pk>", AutoreDetailViewCB.as_view(), name="autore_detail"),
]

news/urls.py
from django.urls import path
from .views import home, ArticoloDetailViewCB, ArticoloListView, GiornalistaDetailViewCB,GiornalistaListView

app_name="news"

urlpatterns=[  
    path('', home, name ="homeview"),
    #path("articoli/<int:pk>", articoloDetailView, name="articolo_detail")
    path("articoli/<int:pk>", ArticoloDetailViewCB.as_view(), name="articolo_detail"),
    path("lista_articoli/", ArticoloListView.as_view(), name="lista_articoli"),
    path("giornalisti/<int:pk>", GiornalistaDetailViewCB.as_view(), name="giornalista_detail"),
    path("lista_giornalisti/", GiornalistaListView.as_view(), name="lista_giornalisti")
]

prima_app/urls.py
from django.urls import path
from .views import homepage, menu, chisiamo, variabili, index
app_name = 'prima_app'
urlpatterns = [

    path('welcome/', homepage, name='home'),
    path('menu/', menu, name='menu'),
    path('chisiamo/', chisiamo, name='chisiamo'),
    path('variabili/', variabili, name='variabili'),
    path('index/', index, name='index'),
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path, include
from prima_app.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index,name='index'),
    path('prima_app/', include('prima_app.urls')),
    path('seconda_app/', include('seconda_app.urls')),
    path('news/', include('news.urls')),
    path('libreria/', include('libreria.urls')),
    path('forms_app/', include('forms_app.urls')),
]

#aggiungiamo a djbango l'authentication url: 
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

seconda_app/urls.py
from django.urls import path
from .views import es_if,es_ifelse, es_elif, esfor
app_name = 'seconda_app'
urlpatterns = [
    path('if', es_if, name='if'),
    path('ifelse', es_ifelse, name='ifelse'),
    path('ifelif', es_elif, name='elif'),
    path('for', esfor, name='for'),
]

templates/base.html
{%load static%}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>{% block title %} My project {% endblock title %}</title>
  </head>
  <body>
    {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Menu</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Prima app
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'prima_app:index'%}">Index</a>
          <a class="dropdown-item" href="{% url 'prima_app:menu'%}">menu</a>
          <a class="dropdown-item" href="{% url 'prima_app:chisiamo'%}">Chi siamo</a>
          <a class="dropdown-item" href="{% url 'prima_app:variabili'%}">variabili</a>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Seconda app
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'seconda_app:for'%}">esercizio for</a>
          <a class="dropdown-item" href="{% url 'seconda_app:if'%}">esercizio if</a>
          <a class="dropdown-item" href="{% url 'seconda_app:elif'%}">esercizio ifelif</a>
          <a class="dropdown-item" href="{% url 'seconda_app:ifelse'%}">esercizio ifelse</a>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          News
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href=http://127.0.0.1:8000/news/lista_articoli>lista articoli</a>
          <a class="dropdown-item" href=http://127.0.0.1:8000/news/lista_giornalisti>lista giornalisti</a>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Libreria
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'libreria:lista_libri'%}">lista libri</a>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Form
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'forms_app:contatti'%}">contatto</a>
        </div>
      </li>

      


    </ul>
  </div>
</nav>
    {% endblock navbar %}


    <div class='container'>
    {%block content%} {%endblock content%}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

  </body>
</html>